USE DietApp
GO

DELETE FROM defaultNutritionalValues 

INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Arctic char, boiled',119,20,0,4)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Bass, mixed species, baked or broiled',110,18,0,4)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Burbot (loche), raw',71,16,0,1)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Catfish, channel, farmed, baked or broiled',114,14,0,6)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Cisco (lake herring, tullibee), baked or broiled',98,17,0,3)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Cisco (lake herring, tullibee), raw',88,17,0,2)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Cod, Atlantic, baked or broiled',79,17,0,1)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Cod, Atlantic, dried and salted, soaked in water',62,13,0,1)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Gefiltefish',63,7,6,1)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Grayling, baked or broiled',80,17,0,1)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Haddock, baked or broiled',84,18,0,1)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Halibut, Atlantic and Pacific, baked or broiled',105,20,0,2)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Herring, Atlantic, kippered',163,18,0,9)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Mackerel, Atlantic, baked or broiled',197,18,0,13)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Ocean Perch, Atlantic, baked or broiled',91,18,0,2)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Pickerel (Walleye), baked or broiled',89,18,0,1)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Pike, northern, baked or broiled',71,16,0,1)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Pollock, Atlantic, baked or broiled',89,19,0,1)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Salmon, Atlantic, farmed, baked or broiled',155,17,0,9)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Salmon, chum (keta), baked or broiled',116,19,0,4)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Salmon, coho, farmed, baked or broiled',134,18,0,6)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Salmon, eggs, raw',116,24,0,9)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Salmon, king or chinook, smoked, canned',113,17,1,4)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Salmon, pink, canned, drained solids with bone',102,17,0,4)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Salmon, smoked',47,7,0,2)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Salmon, smoked, lox',47,7,0,2)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Salmon, sockeye, baked or broiled',162,20,0,8)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Smelt, breaded and fried',201,17,10,10)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Snapper, mixed species, baked or broiled',96,20,0,1)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Sole (flatfish), baked or broiled',88,18,0,1)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Trout, rainbow, farmed, baked or broiled',127,18,0,5)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Tuna, light, canned in water, drained, salted',87,19,0,1)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Tuna, light, canned with oil, drained, salted',149,22,0,6)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Turbot, baked or broiled',92,15,0,3)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Whitefish, lake, native, baked',100,17,0,3)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Clams, mixed species, boiled or steamed',89,15,3,1)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Clams, mixed species, canned, drained solids',125,22,4,2)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Crab, canned, drained',71,15,0,1)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Crab, snow, boiled or steamed',72,15,0,1)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Crayfish, mixed species, farmed, boiled or steamed',52,11,0,1)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Lobster, boiled or steamed',75,16,1,0)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Mussels, boiled or steamed',129,18,6,3)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Oysters, boiled or steamed',58,6,3,2)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Oysters, canned, solids and liquid',90,9,5,3)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Oysters, raw',50,4,5,1)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Scallops, cooked, steamed',87,18,0,1)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Shrimp, boiled or steamed',30,6,0,0)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Calamari, breaded and fried',156,14,9,7)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Caviar, black or red',41,4,1,3)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Crab cake',93,12,0,5)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Crab, imitation, made from surimi',68,8,7,1)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Fish cake',240,16,15,12)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Fish fillet, battered and fried',265,22,9,15)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Shrimp, breaded and fried',160,14,8,8)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Tuna salad',203,17,10,10)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Apple with skin (7cm.diam)',72,0,19,14)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Applesauce, unsweetened',55,0,15,13)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Apricots, dried',67,1,17,0)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Apricots, raw',50,1,12,10)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Avocado',161,2,9,1)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Banana',105,1,27,14)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Blackberries',33,1,7,4)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Blueberries, frozen, unsweetened',42,0,10,7)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Blueberries, raw',44,1,11,8)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Cherries, sweet',43,1,11,9)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Clementine',35,1,9,7)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Cranberries, dried, sweetened',95,0,25,20)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Dates, dried',70,1,19,16)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Figs, dried',42,1,11,8)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Figs, raw',37,0,10,8)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Fruit cocktail, canned, juice pack',58,1,15,14)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Fruit cocktail, canned, light syrup pack',73,1,19,18)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Fruit salad, tropical, canned, heavy syrup pack',117,1,30,0)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Fruit salad, tropical, canned, juice pack',70,1,18,16)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Grapefruit, pink or red',52,1,13,8)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Grapefruit, white',39,1,10,9)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Grapes',69,1,18,15)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Groundcherries',26,1,5,0)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Kiwifruit',46,1,11,7)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Lychees (litchis)',63,1,16,15)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Mango',67,1,18,15)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Melon, cantaloupe, cubes',29,1,7,7)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Melon, honeydew, cubes',32,0,8,7)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Melon, watermelon, cubes',24,0,6,5)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Nectarine',60,1,14,11)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Orange',62,1,15,12)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Papaya, cubes',29,0,7,4)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Peach',38,1,9,8)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Peach, canned halves or slices, juice pack',58,1,15,14)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Peach, canned halves or slices, light syrup pack',72,1,19,18)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Peach, canned halves or slices, water pack',31,1,8,6)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Pear with skin',96,1,26,16)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Pear, canned halves, juice pack',66,0,17,13)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Pear, canned halves, light syrup pack',76,0,20,16)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Pear, canned halves, water pack',37,0,10,8)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Pineapple, canned, juice pack',79,1,21,19)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Pineapple, cubes',42,0,11,8)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Plantain, baked or boiled, sliced',94,1,25,11)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Plum',30,0,8,7)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Pomegranate (9.5cm diam)',53,1,13,13)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Prunes, dried',60,1,16,10)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Prunes, dried, cooked, without added sugar',67,1,18,16)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Raisins',110,1,29,22)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Raspberries',34,1,8,3)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Rhubarb, frozen, cooked, with added sugar',147,0,40,36)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Strawberries',27,1,6,4)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Strawberries, frozen, unsweetened',41,1,11,5)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Tangerine (mandarin)',45,1,11,9)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Tangerine (mandarin), canned, juice pack, drained',38,1,9,8)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Apple juice, ready-to-drink, vitamin C added',59,0,15,14)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Cranberry juice, unsweetened, ready-to-drink',61,1,16,16)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Lemon juice, canned or bottled',3,0,1,0)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Lime juice, canned or bottled',3,0,1,0)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Nectar, apricot',74,0,19,18)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Nectar, mango',68,0,17,17)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Orange and grapefruit juice, ready-to-drink',56,1,13,13)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Orange juice, frozen, diluted',59,1,14,11)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Orange juice, ready-to-drink',58,1,13,0)             
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Pineapple juice, ready-to-drink, vitamin C added',74,0,18,13)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Pomegranate juice, ready-to-drink',72,0,20,17)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Prune juice, ready-to-drink',96,1,24,22)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Alfalfa sprouts, raw',2,0,0,0)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Artichoke hearts, canned in water',13,1,3,0)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Artichoke hearts, marinated in oil',27,1,3,0)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Artichoke, boiled, drained',60,4,13,1)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Asparagus, canned, drained',21,2,3,1)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Asparagus, fresh or frozen, boiled, drained',18,2,3,1)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Bean sprouts, stir-fried',33,3,7,0)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Beans, lima, frozen, boiled, drained',100,6,18,1)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Beets, pickled, sliced, not drained',78,1,20,0)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Beets, sliced, boiled, drained',40,2,9,7)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Beets, sliced, canned, drained',28,1,6,5)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Belgium endive, raw',9,0,2,0)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Bok Choy, Pak-Choi, shredded, boiled, drained',11,1,2,1)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Broccoli, chopped, boiled, drained',29,2,6,1)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Broccoli, chopped, raw',16,1,3,1)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Broccoli, frozen spears, boiled, drained',27,3,5,1)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Brussels sprouts, fresh or frozen, boiled, drained',33,3,6,2)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Cabbage, green, shredded, boiled, drained',17,1,4,2)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Cabbage, green, shredded, raw',9,1,2,1)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Cabbage, napa, shredded, boiled, drained',7,1,1,0)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Cabbage, red, shredded, raw',11,1,3,1)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Carrots, baby, raw',28,1,7,4)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Carrots, fresh or frozen, boiled, drained',28,1,6,3)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Carrots, raw',25,1,6,3)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Cauliflower, pieces, boiled, drained',15,1,3,1)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Cauliflower, pieces, raw',13,1,3,1)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Celery, raw',6,0,1,1)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Corn, sweet, canned, cream style',97,2,25,4)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Corn, sweet, canned, niblets',88,3,22,4)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Cucumber, peeled, raw',3,0,1,0)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Edamame',100,9,8,2)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Eggplant, pieces, boiled, drained',18,0,5,2)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Fiddleheads, frozen, boiled',33,4,6,0)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Fireweed leaves, raw',13,1,2,0)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Hearts of palm, canned',18,2,3,0)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Kale, chopped, boiled, drained',19,1,4,1)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Leeks, chopped, boiled, drained',17,0,4,0)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Lettuce, Boston, shredded',8,1,1,1)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Lettuce, iceberg, shredded',8,1,2,1)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Lettuce, looseleaf, shredded',9,1,2,0)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Lettuce, romaine, shredded',10,1,2,1)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Lettuce, spring mix (mesclun)',12,1,2,0)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Mushrooms, pieces, canned, drained',21,2,4,2)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Mushrooms, portobello, grilled',30,4,4,0)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Mushrooms, raw',12,2,2,1)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Mushrooms, shiitake, sliced, stir-fried',27,2,4,0)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Mushrooms, white, sliced, stir-fried',15,2,2,0)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Onions, green (scallion), raw',5,0,1,0)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Onions, yellow, chopped, raw',17,0,4,2)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Onions, yellow, chopped, sauteed',61,0,4,2)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Parsnip, sliced, boiled, drained',59,1,14,4)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Peas, green, canned, drained',62,4,11,4)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Peas, green, frozen, boiled, drained',66,4,12,4)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Peas, snowpeas, boiled, drained',36,3,6,3)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Peas, snowpeas, raw',14,1,3,1)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Pepper, jalapeno, raw',4,0,1,0)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Pepper, sweet, green, raw',16,1,4,2)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Pepper, sweet, green, sauteed',95,1,3,2)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Pepper, sweet, red, raw',15,1,4,2)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Pepper, sweet, red, sauteed',99,1,5,3)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Pepper, sweet, yellow, raw',25,1,6,0)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Pepper, sweet, yellow, sauteed',36,1,5,0)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Potato, baked, flesh',145,3,34,3)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Potato, baked, flesh and skin',161,4,37,2)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Potato, boiled without skin',116,2,27,1)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Potato, boiled, flesh and skin',129,3,30,1)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Potato, canned, drained',84,2,19,0)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Potato, microwaved, flesh and skin',212,5,49,0)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Potato, microwaved, peeled after cooking',156,3,36,0)  
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Potatoes, scalloped, homemade',111,4,14,0)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Pumpkin, canned',44,1,10,4)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Radicchio, chopped',5,0,1,0)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Radishes',2,0,0,0)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Sauerkraut, canned, not drained',14,1,3,1)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Seaweed, dulse, dried',8,1,1,0)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Spinach, boiled, drained',22,3,4,0)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Spinach, chopped, raw',7,1,1,0)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Squash, acorn, cubed, baked',61,1,16,0)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Squash, butternut, cubed, baked',43,1,11,2)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Squash, spaghetti, baked',22,1,5,2)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Sweet potato, baked, peeled after cooking',51,1,12,5)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Sweet potato, boiled without skin',57,1,13,4)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Swiss chard, chopped, boiled, drained',18,2,4,1)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Tomatoes, canned, stewed',35,1,8,6)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Tomatoes, canned, whole',22,1,5,3)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Tomatoes, raw',22,1,5,3)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Tomatoes, sun-dried',5,0,1,1)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Tomatoes, sun-dried, packed in oil, drained',6,0,1,0)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Turnip (white turnip), cubed, boiled, drained',18,1,4,2)     
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Zucchini, raw, slices',6,0,1,1)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Zucchini, sliced, boiled, drained',15,1,4,2)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Carrot juice',50,1,12,5)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Coleslaw with dressing, homemade',44,1,8,0)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Potato salad, homemade',205,4,14,3)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Tomato clam cocktail',61,1,14,4)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Tomato juice',22,1,5,5)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Tomato juice, without added salt',31,1,8,7)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Tomato sauce for spaghetti, canned',143,2,21,0)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Tomato sauce, canned',41,2,10,6)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Vegetable juice cocktail',24,1,6,4)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Vegetable juice cocktail, low sodium',28,1,6,5)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Chickpea flour',188,11,28,5)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Cornmeal, dry',267,6,57,1)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Oat bran, dry',122,9,33,1)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Oat flakes, dry',200,7,35,1)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Potato flour',302,6,70,3)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Rice flour',305,5,67,0)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Rye flour, light',198,5,43,1)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Soy flour',174,25,20,11)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Wheat bran',8,1,2,0)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Wheat flour, all purpose',240,7,50,0)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Wheat flour, bread',261,9,52,0)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Wheat flour, cake',262,6,56,0)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Wheat flour, whole grain',215,9,46,0)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Wheat germ, toasted',27,2,4,1)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Bagel, plain (10cm diam)',195,7,38,4)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Bannock',84,2,19,0)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Bread, French or Vienna',96,3,18,0)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Bread, Italian',95,3,18,0)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Bread, mixed-grain',88,4,16,4)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Bread, naan',192,7,36,2)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Bread, oatmeal',94,3,17,3)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Bread, pita, white (17cm diam)',165,5,33,1)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Bread, pita, whole wheat (17cm diam)',170,6,35,1)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Bread, pumpernickel',88,3,17,0)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Bread, raisin',96,3,18,2)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Bread, rye',91,3,17,1)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Bread, white, calorie-reduced',72,3,16,2)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Bread, white, commercial',93,3,18,2)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Bread, white, homemade with 2% milk',100,3,17,0)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Bread, whole wheat, commercial',86,3,16,7)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Bread, whole wheat, homemade with 2% milk',97,3,18,1)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Dumpling',69,1,8,0)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('English muffin, white, toasted',133,4,26,2)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('English muffin, whole wheat, toasted',126,5,25,1)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Fry bread, Navajo',122,2,18,1)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Roll, crusty (kaiser)',167,6,30,1)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Roll, dinner, white',85,2,14,2)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Roll, dinner, whole wheat',75,2,14,2)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Roll, hamburger or hotdog, white',120,4,21,3)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Roll, hamburger or hotdog, whole-wheat',113,4,19,3)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Bread stick, plain (19cm X 2cm)',41,1,7,0)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Bread stuffing, dry mix, prepared',188,3,23,2)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Croutons, plain',31,1,6,0)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Matzo, plain',112,3,24,0)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Taco shell, baked (13cm diam)',61,1,8,0)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Tortilla, corn (15cm diam)',41,1,8,0)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Tortilla, wheat (20cm diam)',159,4,27,0)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('French toast, frozen, ready to heat, heated',126,4,19,0)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('French toast, homemade',149,5,16,0)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Pancake, buckwheat, prepared from mix (13cm diam)',73,3,10,2)   
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Pancake, plain, homemade (13cm diam)',86,2,11,0)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Potato pancake, homemade (8cm diam)',112,2,13,1)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Waffle, homemade',103,3,14,2)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Waffle, plain, frozen, ready to heat, heated',87,2,13,2)            
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Barley, pearled, cooked',102,2,23,0)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Bulgur, cooked',80,3,18,0)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Couscous,cooked',93,3,19,0)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Macaroni, cooked',209,7,42,1)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Noodles, Chinese, chow mein',251,4,27,0)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Noodles, egg, cooked',225,8,42,1)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Pasta, fresh-refrigerated, cooked',220,9,40,0)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Pasta, fresh-refrigerated, spinach, cooked',223,9,41,1)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Quinoa, cooked',70,2,13,0)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Ramen noodles, chicken flavour, dry',371,9,54,1)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Rice noodles, cooked',203,2,46,0)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Rice, brown, long-grain, cooked',115,3,24,0)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Rice, white, long-grain, cooked',109,2,24,0)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Rice, white, long-grain, instant, prepared',85,2,19,0)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Rice, white, long-grain, parboiled,cooked',105,2,23,0)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Rice, wild, cooked',88,3,18,1)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Soba noodles, cooked',119,6,26,0)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Spaghetti, cooked',209,7,42,1)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Spaghetti, whole-wheat, cooked',183,8,39,1)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('All Bran Buds with psyllium, Kellogg',70,2,22,7)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('All Bran, Kellogg',92,4,27,6)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Almond Raisin Muslix, Kellogg',173,4,34,13)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Alpha-Bits, PostTM',139,2,30,14)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Bran Flakes, PostTM',185,5,41,9)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Capn Crunch, QuakerTM',108,1,23,10)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Cheerios: Honey Nut, General MillsTM',134,3,28,12)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Cheerios: regular General MillsTM',95,3,18,1)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Cinnamon Toast Crunch, General MillsTM',123,1,22,9)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Corn Bran, QuakerTM',124,3,30,8)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Corn Flakes, KelloggsTM',103,2,23,2)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Corn Pops, KelloggsTM',130,1,30,12)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Cream of wheat, regular',46,2,9,0)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Fibre 1, General MillsTM',79,3,24,0)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Froot Loops, KelloggsTM',116,1,26,14)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Frosted Flakes, KelloggsTM',142,2,33,15)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Fruit & Fibre, Dates/Raisins/Walnuts, PostTM',93,3,22,7)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Granola with Raisins, low fat, KelloggsTM',226,5,46,17)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Granola with Raisins, RogersTM',245,5,41,0)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Grape-Nuts, PostTM',208,6,46,5)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Harvest Crunch, regular, QuakerTM',218,5,31,12)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Honeycomb, PostTM',92,1,21,8)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Just Right, KelloggsTM',172,4,38,10)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Life, QuakerTM',124,5,23,7)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Lucky Charms, General MillsTM',132,2,28,15)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Mini-Wheats with White Frosting, KelloggsTM',121,3,29,3)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Muesli, Presidents ChoiceTM',144,5,28,10)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Nesquik, General MillsTM',120,1,27,14)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Oat bran, cooked',73,3,12,0)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Oatmeal Crisp Almond, General MillsTM',131,3,23,8)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Oatmeal Crisp Maple Walnut, General MillsTM',133,3,25,9)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Oatmeal, instant, apple-cinnamon',141,3,29,12)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Oatmeal, instant, regular',112,4,20,1)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Oatmeal, large flakes/quick',99,4,17,0)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Puffed Wheat, QuakerTM',45,2,9,0)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Raisin Bran, KelloggsTM',187,5,47,17)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Red River, Robin HoodTM',115,4,24,0)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Reeses Puffs, General MillsTM',128,2,24,13)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Rice Krispies, KelloggsTM',110,2,24,3)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Shredded Wheat, PostTM',91,3,21,0)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Shreddies, PostTM',138,4,32,6)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Special K, KelloggsTM',94,4,18,2)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Sugar Crisp, PostTM',103,1,24,14)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Trix, General MillsTM',117,1,27,13)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('WeetabixTM',130,4,29,2)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Cheese crackers',20,0,2,0)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Melba toast, plain',39,1,8,0)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Milk crackers',218,4,33,8)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Rusk toast',41,1,7,0)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Rye wafers, plain',84,2,20,0)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Saltine (oyster, soda, soup)',51,1,9,0)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Saltine (oyster, soda, soup), unsalted top',52,1,9,0)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Standard-type (snack-type) (RitzTM)',60,1,7,0)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Standard-type, reduced sodium (RitzTM)',60,1,7,0)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Wheat crackers',95,2,13,1)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Wheat crackers, low fat',79,2,12,2)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Whole-wheat crackers',71,1,11,0)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Biscuit, plain or buttermilk, fast food',186,3,25,2)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Biscuit, plain or buttermilk, from mix, baked',97,2,14,3)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Biscuit, plain or buttermilk, homemade',212,4,27,1)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Biscuit, plain, refrigerated dough, baked',93,2,13,0)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Croissant, butter',231,5,26,6)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Muffin, blueberry, from mix, prepared',149,3,24,0)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Muffin, bran, from mix, prepared',159,4,27,0)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Muffin, bran, homemade',199,4,32,13)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Muffin, carrot, commercial',344,7,49,17)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Muffin, chocolate chip, commercial',366,8,53,16)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Muffin, fruit, commercial',313,6,54,22)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Muffin, fruit, homemade',162,4,23,0)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Breakfast bar, Oatmeal to GoTM',197,3,33,10)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Cereal bar, fruit filled, Nutri-GrainTM',135,2,26,14)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Chocolate chip, commercial',98,1,13,7)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Chocolate chip, homemade',156,2,19,0)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Chocolate chip, refrigerated dough, baked',118,1,16,0)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Chocolate coated marshmallow',129,1,21,14)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Chocolate sandwich',93,1,14,8)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Coconut macaroons, homemade',194,2,35,34)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Fig',111,1,23,15)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Ginger snaps',58,1,11,3)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Graham crackers, plain or honey',59,1,11,4)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Granola bar, hard, chocolate chip',105,2,17,0)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Granola bar, hard, plain',118,3,16,0)      
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Granola bar, soft, nuts and raisins',127,2,18,0)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Granola bar, soft, peanut butter, chocolate coated',188,4,20,0)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Granola bar, soft, plain',124,2,19,0)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Molasses',129,2,22,5)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Muffin bar (Hop&GoTM, Sweet MorningsTM)',178,2,30,18)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Oatmeal, with raisins, commercial',117,2,18,6)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Oatmeal, without raisins, homemade',134,2,20,0)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Peanut butter sandwich',134,2,18,10)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Peanut butter, homemade',190,4,24,0)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Shortbread, commercial, plain',80,1,10,2)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Shortbread, homemade',185,2,19,7)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Social TeaTM',45,1,7,1)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Sugar cookies, commercial',143,2,20,11)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Sugar cookies, homemade',142,2,25,16)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Vanilla wafers',57,1,9,0)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Angelfood, commercial (25cm diam)',73,2,16,0)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Angelfood, from mix (25cm diam)',129,3,29,15)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Banana bread, homemade (11cm X 6cm X 1cm)',196,3,33,0)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Boston cream pie, commercial',232,2,39,33)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Brownies, commercial (5cm X 5cm)',138,2,22,12)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Brownies, homemade (5cm X 5cm)',168,2,18,0)      
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Gingerbread, from mix (23cm X 23cm)',212,3,35,22)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Pound cake, homemade  (23cm X 13cm X 7.5cm)',391,5,42,22)   
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Sponge, commercial, individual shell',72,1,15,9)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Sponge, homemade (25cm diam)',187,5,36,0)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('White, from mix, with icing (2 layer, 23cm diam)',363,3,66,51)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('White, homemade, with icing (2 layer, 23cm diam)',371,3,70,56)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Yellow, from mix, with icing (2 layer, 23cm diam)',363,4,64,47)             
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Apple, commercial, 2 crust (23cm diam)',296,2,43,20)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Apple, homemade, 2 crust (23cm diam)',411,4,58,0)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Banana cream, from mix, no-bake type (23cm diam)',231,3,29,0)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Butter tart',248,2,29,15)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Cherry, commercial, 2 crust (23cm diam)',325,3,50,18)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Chocolate cream, commercial (20cm diam)',344,3,38,0)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Coconut cream, commercial (20cm diam)',191,1,24,23)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Fried pie, fruit (13cm X 10cm)',404,4,55,27)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Lemon meringue, commercial (20cm diam)',303,2,53,27)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Mincemeat pie, homemade, 2 crust (23cm diam)',477,4,79,47)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Pecan, commercial (20cm diam)',452,5,65,32)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Pumpkin, commercial (20cm diam)',229,4,30,15)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Sugar pie, homemade, 1 crust',407,3,31,18)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Apple crisp, homemade',206,2,39,25)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Bread pudding with raisins, homemade',162,6,24,15)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Danish pastry, cinnamon (11cm diam)',262,5,29,13)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Danish pastry, fruit (11cm diam)',263,4,34,20)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Date squares, homemade',226,3,37,0)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Doughnut, cake-type, plain (8cm diam)',198,2,23,11)    
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Milk shake, chocolate',223,6,36,33)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Milk shake, vanilla',195,6,31,31)           
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('French fries',236,3,29,0)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Garlic Bread',192,5,26,0)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Onion rings, breaded and fried',276,4,31,0)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Zucchini, breaded and fried, sticks',60,1,3,1)      
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Donair / Gyro',310,22,37,3)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Fish sandwich with breaded fish',523,21,48,0)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Hamburger, double patty + condiments',576,32,39,0)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Hamburger, single patty, plain',275,12,31,5)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Submarine sandwich (6 inches), vegetarian',216,7,38,3)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Submarine sandwich (6 inches), with cold cuts',456,22,51,0)    
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Submarine sandwich (6 inches), with tuna',584,30,55,0)    
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Wrap sandwich, chicken ranch',532,32,44,3)          
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Beef and broccoli stir fry',266,24,9,1)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Chicken almond guy ding',295,22,18,3)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Chicken chow mein',200,21,10,7)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Chicken fried rice',343,12,44,1)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Egg roll',113,5,9,1)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('General Tao/Tso chicken',806,50,8,3)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Hot and sour soup',167,17,5,1)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Sweet and sour chicken balls',199,9,17,7)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Won ton soup',191,15,15,1)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Pizza with cheese (medium - 12 inches)',210,9,25,2)    
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Chili con carne',270,26,23,0)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Corndog (PogoTM)',460,17,56,0)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Hot-dog, plain',242,10,18,0)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Meatless breaded chicken nuggets',168,15,6,0)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Meatless ground beef',148,16,6,1)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Soy patty',136,15,5,1)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Tofu, regular, firm and extra firm',189,21,3,1)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Tofu, silken, soft',83,7,4,2)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Vegetable patty',138,18,7,0)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Vegetarian luncheon meat',106,10,2,1)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Wiener, meatless',163,14,5,0)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Beans, baked, homemade',283,10,40,0)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Beans, baked, plain or vegetarian, canned',177,9,40,17)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Beans, baked, with pork, canned',198,10,37,0)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Beans, black, canned, not drained',162,11,29,0)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Beans, kidney, dark red, canned, not drained',161,10,30,0)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Beans, navy, canned, not drained',219,15,40,1)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Beans, pinto, canned, not drained',153,9,27,0)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Beans, refried, canned',175,10,29,0)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Beans, white, canned, not drained',227,14,43,0)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Black-eyed peas, canned, not drained',137,8,24,0)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Chickpeas (garbanzo beans), canned, not drained',211,9,40,0)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Falafel, homemade',57,2,5,0)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Hummus, commercial',94,4,8,0)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Lentils, boiled, salted',170,13,29,3)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Lentils, pink, boiled',190,14,32,0)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Peas, split, boiled',171,12,31,4)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Soybeans, boiled',220,21,13,4)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Almonds, dried',208,8,7,2)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Almonds, oil roasted',242,8,7,2)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Almonds, roasted, salted',209,8,7,2)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Brazil nuts, dried',233,5,4,1)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Cashews, roasted, salted',199,5,11,2)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Hazelnuts or filberts, dried',215,5,6,1)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Mixed nuts, oil roasted, salted',222,6,8,2)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Mixed nuts, roasted',206,6,9,0)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Mixed nuts, roasted, salted',206,6,9,2)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Nuts, macadamia, roasted, salted',243,3,4,1)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Pecans, dried',173,2,3,1)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Pine nuts, pignolia, dried',230,5,4,1)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Pistachios, shelled, roasted, salted',177,7,8,2)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Walnuts, dried',166,4,3,1)           
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Almond butter',205,5,7,0)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Cashew butter',190,6,9,0)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Sesame butter, tahini',181,5,6,0)          
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Flaxseeds, whole and ground',56,2,3,0)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Pumpkin and squash seeds, kernels, dried',189,9,6,0)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Sunflower seed kernels, roasted, salted',189,6,8,1)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Maple syrup',55,0,14,12)             
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Pancake syrup',47,0,12,7)             
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Double fruit jam type spread',42,0,10,9)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Double fruit jam type spread, reduced sugar',23,0,5,5)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Jams and preserves',56,0,14,10)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Jelly',56,0,15,11)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Marmalade',50,0,13,12)            
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Chocolate topping, fudge-type',135,2,24,13)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Pie filling, cherry, canned',29,0,7,0)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Spread, chocolate hazelnut (NutellaTM)',36,0,4,4)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Topping or spread, butterscotch',105,1,27,0)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Topping, strawberry',110,0,29,12)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Butterscotch',21,0,5,4)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Candy, chocolate covered, sweetened with sorbitol',29,1,2,1)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Caramel',154,2,31,26)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Chewing gum',7,0,2,2)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Chewing gum, sugarless',5,0,2,0)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Fruit leather',52,0,12,7)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Fudge, chocolate, homemade',70,0,13,13)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Fudge, vanilla, homemade',84,0,18,18)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Gumdrops',143,0,36,21)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Hard candy',24,0,6,4)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Hard candy, reduced sugar',11,0,3,3)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Jellybeans',105,0,26,20)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Licorice, strawberry (TwizzlersTM)',132,1,30,15)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Marshmallows',23,0,6,4)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Sesame crunch',181,4,18,11)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('SkittlesTM',43,0,10,8)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Toffee',67,0,8,8)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Almonds, chocolate covered',180,4,15,12)        
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Ice cream cone, vanilla, soft serve',266,7,43,32)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Ice cream sandwich',143,3,22,14)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Ice cream, chocolate',151,3,20,18)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Ice cream, dairy free',237,4,21,0)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Ice cream, strawberry',134,2,19,0)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Ice cream, vanilla, low fat',117,5,20,10)      
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Ice cream, vanilla, premium',282,4,25,23)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Ice cream, vanilla, regular',153,3,18,16)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Popsicles',54,0,14,10)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Sherbet, orange',113,1,24,19)            
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Chocolate mousse, homemade',480,9,34,32)     
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Gelatin dessert, prepared (JelloTM)',88,2,20,19)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Burrito with beans and cheese',189,8,27,0)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Burrito with beef, cheese and chilli',316,20,32,0)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Nachos with cheese',346,9,36,0)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Quesadilla with meat',627,31,40,0)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Taco salad',193,12,13,2)           
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Club sandwich',558,32,47,5)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Hot chicken sandwich',388,40,31,2)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Sandwich, egg salad',479,14,27,3)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Sandwich, ham',260,13,28,2)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Sandwich, roast beef, plain',346,22,33,0)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Sandwich, salmon salad',340,16,33,5)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Sandwich, tuna salad',371,20,33,5)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Caesar salad',335,9,12,3)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Caesar salad with chicken',491,41,12,3)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Garden Salad',47,1,4,3)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Greek Salad',139,4,4,2)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Pasta salad with vegetables',245,5,33,5)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Lasagna with meat (7.5cm x 9cm)',364,22,37,6)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Lasagna, vegetarian (7.5cm x 9cm)',355,19,46,7)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Macaroni and cheese (Kraft DinnerTM)',395,11,49,6)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Macaroni casserole with beef and tomato soup',319,23,32,6)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Spaghetti with cream sauce',250,9,47,4)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Spaghetti with meat sauce',401,19,50,9)           
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Beef pot pie, commercial, individual',638,18,57,0)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Beef stew',168,18,14,3)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Butter chicken',368,28,13,4)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Chicken fajita',350,19,50,3)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Chicken pot pie, commercial, individual',494,21,37,3)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Pad Thaï',220,15,26,4)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Poutine',380,13,25,1)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Samosa, vegetarian',306,5,32,1)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Shepherds pie',389,17,40,5)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Stir fry with beef',290,22,20,11)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Stir fry with chicken',255,18,8,2)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Stir fry with tofu',183,14,10,3)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Sushi with fish',164,5,35,7)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Sushi with vegetables, no fish',122,2,27,5)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Sweet and sour meatballs',472,26,33,19)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Tourtiere, homemade (20cm diam)',307,15,23,1)            
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Potato chips, baked, plain',202,2,31,2)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Potato chips, flavoured',211,3,23,0)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Potato chips, plain',230,3,21,0)   
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Tortilla chips, plain',234,3,29,0)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Banana chips',73,0,8,5)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Beef jerky (22cm long)',81,7,2,2)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Beer nuts',186,8,10,5)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Fruit leather bar (Fruit to GoTM)',49,0,11,0)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Pretzels, hard, plain, salted',19,0,4,0)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Pretzels, hard, plain, unsalted',191,5,40,1)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Rice cakes, plain',35,1,7,0)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Sesame sticks, salted',75,2,6,0)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Soybeans, roasted, salted',205,15,15,2)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Trail mix, regular',176,5,17,0)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Trail mix, tropical',144,2,23,0)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Chai, latte',149,5,26,26)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Coffee, brewed',2.5,0,0,0)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Coffee, brewed, decaffeinated',2.5,0,0,0)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Coffee, instant, regular, powder + water',5,0,1,0)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Coffee, latte',101,5,7,9)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Coffee, substitute, powder + water',13,0,3,0)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Iced cappuccino - with 2% milk (Tim HortonsTM)',127,3,27,27)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Iced coffee, Frappuccino (StarbucksTM)',127,3,26,22)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Iced tea, lemon flavor, ready-to-drink',91,0,23,23)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Iced tea, lemon flavour, powder + water',93,0,23,23)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Tea, brewed',3,0,1,0)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Tea, brewed, herbal',3,0,1,0)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Club soda',0,0,0,0)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Cola',110,0,28,24)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Cola, aspartame sweetened',3,0,0,0)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Cola, decaffeinated',107,0,28,28)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Ginger ale',88,0,23,22)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Lemon-lime soda',104,0,27,23)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Non cola soda, aspartame sweetened',0,0,0,0)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Orange soda',126,0,32,0)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Tonic water',124,0,32,32)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Citrus juice drink, frozen, diluted (Five AliveTM)',131,0,32,30)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Lemonade, pink or white, frozen, diluted',105,0,27,13)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Beer, de-alcoholized, (Labbat .5TM)',210,1,47,28)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Beer, high alcohol (7%alcohol by volume)',183,1,10,0)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Beer, light (4% alcohol by volume)',99,1,5,0)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Beer, regular (5% alcohol by volume)',140,1,10,0)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Cocktail, daiquiri',237,0,9,7)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Cocktail, margarita',246,0,6,4)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Liqueur, coffee and cream',172,1,11,10)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Sangria',87,0,12,10)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Spirits (gin, rum, vodka, whisky)',109,0,0,0)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Vodka cooler',220,0,33,12)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Wine, dessert, sweet',203,0,17,10)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Wine, table, red',90,0,2,1)       
INSERT INTO defaultNutritionalValues (food, calories, protein, carbohydrates, fat) VALUES ('Wine, table, white',85,0,1,1)       